language: ruby
sudo: false
rvm:
  - 2.2.5
  - 2.3.1
  - ruby-head
gemfile:
  - gemfiles/Gemfile-edge
  - Gemfile
notifications:
  email: false
matrix:
  fast_finish: true
  allow_failures:
    - rvm: ruby-head
cache: bundler
